# -----------------------------
# Dockerfile.client
# -----------------------------
FROM node:18-alpine AS build
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client ./
RUN npm run build




FROM nginx:stable

# Копируем кастомный конфиг (обязательно должен быть рядом с Dockerfile)
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Копируем билд React из предыдущего stage
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]